services:
  db:
    image: postgres
    container_name: db
    restart: always 
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - pg:/var/lib/postgresql/data

  node_app:
    container_name: node
    build: . 
    ports:
      - 5002:5000
    depends_on:
      - db 
    env_file:
      - .env 
volumes:  
  pg: